stages:
  - build
  - test
  - deploy

default:
  services:
    - docker:24.0.5-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

build_images:
  stage: build
  image: docker:24.0.5
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $BACKEND_IMAGE ./backend
    - docker push $BACKEND_IMAGE
    - docker build --pull -t $FRONTEND_IMAGE ./frontend
    - docker push $FRONTEND_IMAGE

test_backend:
  stage: test
  image: python:3.11-slim
  script:
    - cd backend
    - pip install -r requirements.txt
    - pytest || echo "Tests ignorés"

test_frontend:
  stage: test
  image: node:18-alpine
  script:
    - cd frontend
    - npm ci
    - npm test -- --watch=false --browsers=ChromeHeadless || echo "Tests ignorés"

deploy_local:
  stage: deploy
  tags:
    - my-pc-runner
  script:
    - echo "Déploiement local..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose down --remove-orphans
    - docker-compose pull
    - docker-compose up -d
  only:
    - main
